.github/workflows/array-api-tests.yml
This is needed until https://github.com/data-apis/array-api-tests/issues/238 is fixed.
=> Temporarily pin hypothesis on CI

array_api_strict/_array_object.py
=> Support `copy` keyword in `__array__` method

array-api-tests-xfails.txt
The test suite is updated so that these tests no longer fail.
=> Remove fft tests from xfails

.github/workflows/dependabot-auto-merge.yml
Dependabot only updates GitHub Actions workflow versions, so there should be little risk in this. It shouldn't actually merge things unless CI passes because of required checks.
=> Add a workflow to automatically merge dependabot updates

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
- Allow 2022.12
- Warn on 2021.12
- Be more strict about only accepting those two versions
=> Update api_version argument to __array_namespace__

array_api_strict/__init__.py, array_api_strict/_array_object.py, array_api_strict/_flags.py, array_api_strict/_linear_algebra_functions.py, array_api_strict/_searching_functions.py, array_api_strict/_set_functions.py, array_api_strict/fft.py, array_api_strict/linalg.py, array_api_strict/tests/conftest.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_flags.py, docs/api.rst, docs/changelog.md, docs/conf.py, docs/index.md
Flags are global variables that set array-api-strict in a specific mode. Currently support flags change the support array API standard version, enable or disable data-dependent shapes, and enable or disable optional extensions.
So far I have only set up the structure for setting and getting these flags. Let me know if this seems like a good API layout or not.
I plan to add functionality to the various functions to enable/disable behaviors depending on what flags are set. 
Fixes #8 
Fixes #7
=> array-api-strict flags

.github/workflows/publish-package.yml
This prevents this workflow from failing on every commit in main.
=> Don't try to run the publish step unless the commit is a tag

array_api_strict/_array_object.py, array_api_strict/_flags.py, array_api_strict/tests/test_flags.py, docs/api.rst
It is separate in the inspection API, so we try to match that.
=> Make boolean_indexing a separate flag from data_dependent_shapes

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
=> Disable array iteration

array_api_strict/_flags.py, docs/api.rst, docs/changelog.md, docs/index.md
This release adds the new flags features and 2023.12 support.
=> array-api-strict 2.0 release

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py, docs/changelog.md
upstream code (see scipy/scipy#21074). The standard does not define iteration, but it does define `__getitem__`, and the default Python `__iter__` implements iteration when getitem is defined as a[0], a[1], ..., implying that iteration ought to work for 1-D arrays. Iteration is still disallowed for higher dimensional arrays, since getitem would not necessarily work with a single integer index (and this is the case that is controversial). In those cases, the new unstack() function would be preferable.
At best it would be good to get upstream clarification from the standard whether iteration should always work or not before disallowing 1-D array iteration.
=> Allow iteration on 1-D arrays

array_api_strict/_array_object.py, array_api_strict/_elementwise_functions.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_elementwise_functions.py
This does not change == or != because the standard is currently unclear about that so I'd like to see what happens there first.
=> Allow any combination of real dtypes in comparisons

array_api_strict/_array_object.py, array_api_strict/_elementwise_functions.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_elementwise_functions.py
Reverts data-apis/array-api-strict#53. The standard is likely going to change to make this undefined. See https://github.com/data-apis/array-api/pull/822.
=> Revert "Allow any combination of real dtypes in comparisons"

README.md, array_api_strict/_flags.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_elementwise_functions.py, array_api_strict/tests/test_flags.py, array_api_strict/tests/test_linalg.py, array_api_strict/tests/test_statistical_functions.py, docs/index.md
SciPy and others have been using it and haven't found any issues. Test suite support is still not 100% but is pretty strong at this point.
=> Make 2023.12 the default version

array_api_strict/_manipulation_functions.py
NumPy does not allow repeats to be uint64 because it refuses to downcast it. Technically it worked before because we implement __array__ and repeat does manually cast in that case. I'm not really sure we should be supporting __array__ actually.
=> Fix issue with repeat()

array_api_strict/_elementwise_functions.py
They were only working because we define __array__, which may be going away (#67).
=> Fix some functions that were missing ._array

array_api_strict/__init__.py, array_api_strict/_array_object.py, array_api_strict/_creation_functions.py, array_api_strict/_data_type_functions.py, array_api_strict/_dtypes.py, array_api_strict/_elementwise_functions.py, array_api_strict/_fft.py, array_api_strict/_indexing_functions.py, array_api_strict/_info.py, array_api_strict/_linalg.py, array_api_strict/_linear_algebra_functions.py, array_api_strict/_manipulation_functions.py, array_api_strict/_searching_functions.py, array_api_strict/_set_functions.py, array_api_strict/_sorting_functions.py, array_api_strict/_statistical_functions.py, array_api_strict/_typing.py, array_api_strict/_utility_functions.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_device_support.py, array_api_strict/tests/test_elementwise_functions.py, array_api_strict/tests/test_indexing_functions.py, array_api_strict/tests/test_sorting_functions.py
Having more than one device is useful during testing to allow you to find bugs related to how arrays on different devices are handled. Closes #56 
With scikit-learn we run into the frustrating situation were contributors execute tests locally, they all pass but then see failures on the CI related to the fact that e.g. PyTorch has several devices and some things work on the CPU device but not on the CUDA/MPS device. However, if you have neither of those on your local machine you can't really test this upfront and to debug it you need to rely on the CI.
The idea of this PR is to add support for multiple devices to `array-api-strict` to make testing easier. The default device continues to be the CPU device and for arrays that use it nothing should change. However, you can now place an array …
=> Add "multi device" support

array_api_strict/_creation_functions.py, array_api_strict/tests/test_creation_functions.py
This fixes the problem reported in #70 (but doesn't close because the issue is more generic).
Simple case of forgetting to propagate the device of the input (if it is an array). I've added a test for this and fixed`full_like` and `empty_like`  where this was missing.
=> FIX Propagate input array's device in `asarray`

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
When promoting a scalar in the context of an existing array, e.g. `x ** 2` we should use the device of `x` for the array we create.
=> FIX Use array's device when promoting scalars

array_api_strict/_elementwise_functions.py
This is based on the implementation from the compat library.
Fixes #75
Closes #49
=> Use a more robust implementation of clip

array_api_strict/_array_object.py, array_api_strict/_creation_functions.py, array_api_strict/_linalg.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_creation_functions.py
This makes it raise an exception, since it isn't supported by the standard (if
we just leave it unimplemented, then np.asarray() returns an object dtype
array, which is not good).
There is one issue here from the test suite, which is that this breaks the
logic in asarray() for converting lists of array_api_strict 0-D arrays. I'm
not yet sure what to do about that.
Fixes https://github.com/data-apis/array-api-strict/issues/67.
This is built on #68, which can and should be merged separately (it isn't controversial).
=> Remove __array__

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
=> Allow __dlpack__ to work with newer versions of NumPy

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
Removing it caused issues for SciPy
(https://github.com/data-apis/array-api-strict/issues/67). I have left the flag in to make it easy to remove it in the future.
I also considered raising a warning in __array__, but this is also difficult to handle https://github.com/data-apis/array-api-strict/pull/91
=> Re-enable __array__

docs/changelog.md
This reverts the NumPy 2.0 and `__array__` removal changes from the releases yesterday. 
Still need to merge https://github.com/data-apis/array-api-strict/pull/92 into this before doing the release.
=> 2.1.3 release

array_api_strict/_data_type_functions.py
as discussed in https://github.com/data-apis/array-api-tests/pull/311 :
the spec stipulates that (https://data-apis.org/array-api/latest/API_specification/generated/array_api.astype.html#astype)
> Casting a complex floating-point array to a real-valued data type should not be permitted.
Thus error out here and avoid testing `astype(complex, not complex)`  it in `-tests`.
=> ENH: prohibit astype(complex, not complex)

array_api_strict/_linear_algebra_functions.py
This is currently untested by the test suite (data-apis/array-api-tests#312)
Fixes #97.
=> Conjugate the first argument in vecdot

array_api_strict/_flags.py
reprod:
```
python -OO -c "import array_api_strict"
```
=> BUG: fix import error against Python's optimized mode

array_api_strict/_statistical_functions.py, array_api_strict/tests/test_statistical_functions.py
Prepare for 2024.12: https://github.com/data-apis/array-api/pull/850/
An incremental follow-up to https://github.com/data-apis/array-api-strict/pull/82/
=> ENH: allow mean(complex) in 2024.12

.gitignore, array_api_strict/_data_type_functions.py, array_api_strict/tests/test_data_type_functions.py
Raise on a typical mistake made by a user that didn't properly read the API documentation (i.e. me):
```python
>>> xp.isdtype(xp.asarray(1.0), xp.float64))
False
```
=> isdtype() should raise if parameter is not a dtype

array_api_strict/_array_object.py
For 0D arrays, `__str__` used to look confusingly like a scalar, make it clearly an array instead.
Before:
```
In [1]: import array_api_strict as xp
In [2]: x = xp.asarray(3)
In [3]: print(x)     # looks like a scalar!
3
In [4]: x.__class__
Out[4]: array_api_strict._array_object.Array
In [5]: x
Out[5]: Array(3, dtype=array_api_strict.int64)
```
This PR:
```
In [1]: import array_api_strict as xp
In [2]: x = xp.asarray(3)
In [3]: print(x)
Array(3, dtype=array_api_strict.int64)
In [4]: x
Out[4]: Array(3, dtype=array_api_strict.int64)
```
=> MAINT: make __str__ less ambiguous

array_api_strict/_array_object.py, array_api_strict/_elementwise_functions.py, array_api_strict/_helpers.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_elementwise_functions.py
=> ENH: allow python scalars in binary elementwise functions

array_api_strict/_searching_functions.py, array_api_strict/tests/test_searching_functions.py
This is related to https://github.com/data-apis/array-api/issues/807
This only adds support for scalars to `where()`. If the second or third argument is a scalar it is turned into an array on the same device as `condition`.
I added `2024.12` as `next_supported_version`. This means we can use it in the tests. Not sure if we use some kind of dummy value instead of 2024.12?
=> Add support for scalar arguments to xp.where

array_api_strict/_fft.py
A companion to https://github.com/data-apis/array-api/pull/885/ [draft until the spec PR lands].
=> ENH: add dtype kwarg to fft.{fftfreq, rfftfreq}

array_api_strict/_data_type_functions.py, array_api_strict/tests/test_data_type_functions.py, array_api_strict/tests/test_manipulation_functions.py, array_api_strict/tests/test_validation.py
as allowed by https://github.com/data-apis/array-api/pull/873
=> Allow python scalars in `result_type`: 2024.12 revision

array_api_strict/_array_object.py, array_api_strict/_dtypes.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_elementwise_functions.py
This is a companion to https://github.com/data-apis/array-api/pull/871
The volume of workarounds to make tests pass is not bad bad bad, but is probably worth a longer look.
Maybe `array._promote_scalar` needs to grow a flag to tell whether mixing complex and floats is allowed for a specific caller.
=> Define complex scalar <op> float array

array_api_strict/_manipulation_functions.py
closes https://github.com/data-apis/array-api-strict/issues/62
Not having `axis=None` is, in fact, a deliberate decision: https://github.com/data-apis/array-api/issues/892
=> MAINT: block axis=None in squeeze

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
cross-ref https://github.com/data-apis/array-api/pull/900
TODO:
=> fancy indexing with ints and integer arrays

array_api_strict/_flags.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_data_type_functions.py, array_api_strict/tests/test_elementwise_functions.py, array_api_strict/tests/test_flags.py, array_api_strict/tests/test_searching_functions.py, array_api_strict/tests/test_statistical_functions.py, docs/changelog.md
TODO:
The name listing is generated via
$ git log 2.2..HEAD --pretty=format:"%an" |sort |uniq
=> release branch 2.3

array_api_strict/_helpers.py, array_api_strict/_searching_functions.py, array_api_strict/tests/test_searching_functions.py
This should be allowed by the spec: python int scalars can combine with float arrays.
fixes https://github.com/data-apis/array-api-strict/issues/131
=> BUG: fix where(cond, float_array, int)

array_api_strict/__init__.py, array_api_strict/_array_object.py, array_api_strict/_constants.py, array_api_strict/_creation_functions.py, array_api_strict/_data_type_functions.py, array_api_strict/_dtypes.py, array_api_strict/_elementwise_functions.py, array_api_strict/_fft.py, array_api_strict/_flags.py, array_api_strict/_helpers.py, array_api_strict/_indexing_functions.py, array_api_strict/_info.py, array_api_strict/_linalg.py, array_api_strict/_linear_algebra_functions.py, array_api_strict/_manipulation_functions.py, array_api_strict/_searching_functions.py, array_api_strict/_set_functions.py, array_api_strict/_sorting_functions.py, array_api_strict/_statistical_functions.py, array_api_strict/_typing.py, array_api_strict/_utility_functions.py, array_api_strict/tests/test_validation.py, pyproject.toml
- Implement thorough static type annotations
- Align type annotations conventions to `array-api-compat` (https://github.com/data-apis/array-api-compat/pull/257)
- Add `py.typed`
- Manually run mypy and fix _most_ typing issues
- Manually run isort (one-off)
- Fix bug where `iinfo` and `finfo` would return a numpy dtype instead of a DType
- Fix _all_ mypy errors (some highlight material issues that deserve their own PRs)
- Add mypy to CI
- Make pyright happy
- tests module
=> TYP: type annotations

.github/workflows/array-api-tests.yml, .github/workflows/tests.yml, array-api-tests-xfails.txt
- stop testing python 3.9
- start testing python 3.13
- actually test Array API revision 2024.12
- stop testing 2022.12 revision (only test 2023.12 and 2024.12)
=> CI: update the workflows

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
closes #134
When indexing with tuple containing `Array`s, convert to numpy array (`self._array`) first. Not doing so results in e.g. "Can not convert array on the 'array_api_strict.Device('device1')' device to a Numpy array." error
Parametrized indexing tests for all devices. Also added shape checks in test because while working on this PR, I created a bug that was not picked up by the test in the current format as the bug also affected the loop arrays.
cc @ev-br
=> BUG: fix tuple array indexing

array_api_strict/_data_type_functions.py, array_api_strict/_dtypes.py, array_api_strict/tests/test_data_type_functions.py
- Follow-up to bugfix to .dtype attribute in #135
- Closes #138
- Closes #116
- Make finfo/iinfo output uncomparable and unwriteable
=> MAINT: finfo() / iinfo() input/output review

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
closes #144
Fixes bug with indexing with integers introduced in https://github.com/data-apis/array-api-strict/pull/139
=> Fix indexing with integers

array_api_strict/_creation_functions.py, array_api_strict/tests/test_array_object.py, array_api_strict/tests/test_creation_functions.py
closes https://github.com/data-apis/array-api-strict/issues/118
A matching PR to clarify the spec: https://github.com/data-apis/array-api/pull/917
Tested locally to not impact scipy. @lucyleeow would you be able to check whether this impacts scikit-learn?
=> BUG: do not allow asarray of nested sequences of arrays

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
In #135, binary operators vs. numpy.int64 became (correctly) disallowed.
Add a test for it.
Also test binary operators vs. numpy.float64 and numpy.complex128, which must be ~allowed as~ rejected even if they are subclasses of float and complex respectively.
The same treatment for functions is in a separate PR: https://github.com/data-apis/array-api-strict/pull/148.
- XREF https://github.com/scipy/scipy/pull/22783
=> ENH: disallow numpy generics

array_api_strict/_array_object.py, array_api_strict/_creation_functions.py, array_api_strict/_data_type_functions.py, array_api_strict/_elementwise_functions.py, array_api_strict/_helpers.py, array_api_strict/_linalg.py, array_api_strict/_searching_functions.py, array_api_strict/_statistical_functions.py
As per consortium meeting, Apr 17th https://hackmd.io/zn5bvdZTQIeJmb3RW1B-8g
=> TYP: Compact Python scalar types

.github/workflows/array-api-tests.yml, array_api_strict/_array_object.py, array_api_strict/_creation_functions.py, array_api_strict/tests/test_array_object.py
Try getting rid of `__array__`, replace with the buffer protocol's `__buffer__`.
cross-ref https://github.com/data-apis/array-api-strict/issues/67, https://github.com/data-apis/array-api-strict/pull/69
This does not seem to fix gh-102. `scipy` tests pass locally. 
Replacing `__array__` with `__buffer__` makes code marginally simpler. Effectively bumps the python requirement to 3.12+ though.
So maybe this is a temp solution until `dlpack` matures. 
`¯\_(ツ)_/¯`
=> ENH: rm __array__, add __buffer__

docs/changelog.md
=> REL: Release 2.4 branch

array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py
A minimal fix for gh-102.
As a byproduct, add several `check_device` calls, where previously missing.
=> BUG: add missing `_check_type_device` calls

.github/workflows/array-api-tests.yml, .github/workflows/tests.yml, array_api_strict/_array_object.py, array_api_strict/tests/test_array_object.py, docs/changelog.md
- Towards #160 (need to release 2.4.1, wait some time, and yank 2.4 to close it)
- Reinstate support for Python 3.10 and 3.11
- Bump NumPy in CI from 2.2 to 2.3
=> Reinstate `__array__` on Python 3.10/3.11
